import {
  FaInstagram,
  FaFacebook,
  FaQuestion,
  FaAccessibleIcon,
  FaAddressBook,
  FaAddressCard,
  FaAdjust,
  FaBaby,
  FaBabyCarriage,
  FaBacteria,
  FaBible,
  FaBook,
  FaBriefcaseMedical,
  FaBuilding,
  FaBus,
  FaCalendar,
  FaCapsules,
  FaCar,
  FaCart,
  FaCat,
  FaCheck,
  FaChild,
  FaClock,
  FaCloud,
  FaDog,
  FaDumbbell,
  FaEnvelope,
  FaEye,
  FaEyeSlash,
  FaFile,
  FaFileAlt,
  FaFileMedical,
  FaFileMedicalAlt,
  FaFilePdf,
  FaFileWord,
  FaFlag,
  FaFlask,
  FaFolder,
  FaFolderOpen,
  FaFrown,
  FaFrownOpen,
  FaGift,
  FaHandHoldingHeart,
  FaHandHoldingMedical,
  FaHandHoldingUsd,
  FaHandHoldingWater,
  FaHandHolding,
  FaHandHeart,
  FaIdBadge,
  FaIdCard,
  FaImage,
  FaImages,
  FaInfo,
  FaInfoCircle,
  FaJournalWhills,
  FaKey,
  FaLaptop,
  FaLaptopMedical,
  FaLeaf,
  FaLifeRing,
  FaLightbulb,
  FaLink,
  FaList,
  FaListAlt,
  FaListOl,
  FaListUl,
  FaMap,
  FaMapMarked,
  FaMapMarkedAlt,
  FaMapMarker,
  FaMapMarkerAlt,
  FaMapPin,
  FaMapSigns,
  FaMedal,
  FaMedical,
  FaMedicalAlt,
  FaMoneyBill,
  FaMoneyBillAlt,
  FaMoneyBillWave,
  FaMoneyBillWaveAlt,
  FaMoneyCheck,
  FaMoneyCheckAlt,
  FaMoneyCheckEdit,
  FaMoneyCheckEditAlt,
  FaMoon,
  FaNewspaper,
  FaObjectGroup,
  FaObjectUngroup,
  FaOutdent,
  FaPaintBrush,
  FaPaintRoller,
  FaPalette,
  FaPaperPlane,
  FaPaperclip,
  FaParagraph,
  FaPaste,
  FaPause,
  FaPencilAlt,
  FaPeopleCarry,
  FaPercent,
  FaPhone,
  FaPhoneAlt,
  FaPhoneSlash,
  FaPhoneSquare,
  FaPhoneSquareAlt,
  FaPhoneVolume,
  FaPiggyBank,
  FaPills,
  FaPlane,
  FaPlaneArrival,
  FaPlaneDeparture,
  FaPlay,
  FaPlug,
  FaPlus,
  FaPlusCircle,
  FaPlusSquare,
  FaPodcast,
  FaPoll,
  FaPollH,
  FaPoop,
  FaPortrait,
  FaPoundSign,
  FaPowerOff,
  FaPrescription,
  FaPrescriptionBottle,
  FaPrescriptionBottleAlt,
  FaPrint,
  FaProcedures,
  FaProjectDiagram,
  FaPuzzlePiece,
  FaQuestionCircle,
  FaReceipt,
  FaRedo,
  FaRedoAlt,
  FaRegistered,
  FaReply,
  FaReplyAll,
  FaRetweet,
  FaRibbon,
  FaRoad,
  FaRocket,
  FaRss,
  FaRssSquare,
  FaRubleSign,
  FaRupeeSign,
  FaSave,
  FaSchool,
  FaScrewdriver,
  FaSearch,
  FaSearchDollar,
  FaSearchLocation,
  FaSearchMinus,
  FaSearchPlus,
  FaSeedling,
  FaServer,
  FaShare,
  FaShareAlt,
  FaShareAltSquare,
  FaShareSquare,
  FaShieldAlt,
  FaShip,
  FaShippingFast,
  FaShoePrints,
  FaShoppingBag,
  FaShoppingBasket,
  FaShoppingCart,
  FaShower,
  FaShuttleVan,
  FaSign,
  FaSignInAlt,
  FaSignLanguage,
  FaSignOutAlt,
  FaSignal,
  FaSitemap,
  FaSkull,
  FaSlidersH,
  FaSmile,
  FaSmileBeam,
  FaSmileWink,
  FaSnowflake,
  FaSort,
  FaSortAlphaDown,
  FaSortAlphaUp,
  FaSortAmountDown,
  FaSortAmountUp,
  FaSortDown,
  FaSortNumericDown,
  FaSortNumericUp,
  FaSortUp,
  FaSpaceShuttle,
  FaSpinner,
  FaSquare,
  FaStar,
  FaStarHalf,
  FaStepBackward,
  FaStepForward,
  FaStethoscope,
  FaStickyNote,
  FaStop,
  FaStopwatch,
  FaStore,
  FaStoreAlt,
  FaStream,
  FaStreetView,
  FaStrikethrough,
  FaStroopwafel,
  FaSubscript,
  FaSubway,
  FaSuitcase,
  FaSun,
  FaSuperscript,
  FaSync,
  FaSyncAlt,
  FaSyringe,
  FaTable,
  FaTablet,
  FaTabletAlt,
  FaTachometerAlt,
  FaTag,
  FaTags,
  FaTape,
  FaTasks,
  FaTaxi,
  FaTeeth,
  FaTeethOpen,
  FaTerminal,
  FaTextHeight,
  FaTextWidth,
  FaTh,
  FaThLarge,
  FaThList,
  FaThermometer,
  FaThermometerEmpty,
  FaThermometerFull,
  FaThermometerHalf,
  FaThermometerQuarter,
  FaThermometerThreeQuarters,
  FaThumbsDown,
  FaThumbsUp,
  FaThumbtack,
  FaTicketAlt,
  FaTimes,
  FaTimesCircle,
  FaTint,
  FaTintSlash,
  FaTired,
  FaToggleOff,
  FaToggleOn,
  FaToilet,
  FaToiletPaper,
  FaToolbox,
  FaTools,
  FaTooth,
  FaTrademark,
  FaUndo,
  FaUndoAlt,
  FaUniversalAccess,
  FaUniversity,
  FaUnlink,
  FaUnlock,
  FaUnlockAlt,
  FaUpload,
  FaUser,
  FaUserAlt,
  FaUserAltSlash,
  FaUserAstronaut,
  FaUserCheck,
  FaUserCircle,
  FaUserClock,
  FaUserCog,
  FaUserEdit,
  FaUserFriends,
  FaUserGraduate,
  FaUserLock,
  FaUserMd,
  FaUserMinus,
  FaUserNinja,
  FaUserPlus,
  FaUserSecret,
  FaUserShield,
  FaUserSlash,
  FaUserTag,
  FaUserTie,
  FaUserTimes,
  FaUsers,
  FaUsersCog,
  FaUtensilSpoon,
  FaUtensils,
  FaVectorSquare,
  FaVenus,
  FaVenusDouble,
  FaVenusMars,
  FaVial,
  FaVials,
  FaVideo,
  FaVideoSlash,
  FaVihara,
  FaVolumeDown,
  FaVolumeMute,
  FaVolumeOff,
  FaVolumeUp,
  FaWalking,
  FaWallet,
  FaWarehouse,
  FaWeight,
  FaWeightHanging,
  FaWheelchair,
  FaWifi,
  FaWindowClose,
  FaWindowMaximize,
  FaWindowMinimize,
  FaWindowRestore,
  FaWineGlass,
  FaWonSign,
  FaWrench,
  FaXRay,
} from "react-icons/fa";

const icons = {
  Facebook: FaFacebook,
  QuestionMark: FaQuestion,
  Accesible: FaAccessibleIcon,
  AddressBook: FaAddressBook,
  AddressCard: FaAddressCard,
  Adjust: FaAdjust,
  Baby: FaBaby,
  BabyCarriage: FaBabyCarriage,
  Bacteria: FaBacteria,
  Bible: FaBible,
  Book: FaBook,
  BriefcaseMedical: FaBriefcaseMedical,
  Building: FaBuilding,
  Bus: FaBus,
  Calendar: FaCalendar,
  Capsules: FaCapsules,
  Car: FaCar,
  Cart: FaCart,
  Cat: FaCat,
  Check: FaCheck,
  Child: FaChild,
  Clock: FaClock,
  Cloud: FaCloud,
  Dog: FaDog,
  Dumbbell: FaDumbbell,
  Envelope: FaEnvelope,
  Eye: FaEye,
  EyeSlash: FaEyeSlash,
  File: FaFile,
  FileAlt: FaFileAlt,
  FileMedical: FaFileMedical,
  FileMedicalAlt: FaFileMedicalAlt,
  FilePdf: FaFilePdf,
  FileWord: FaFileWord,
  Flag: FaFlag,
  Flask: FaFlask,
  Folder: FaFolder,
  FolderOpen: FaFolderOpen,
  Frown: FaFrown,
  FrownOpen: FaFrownOpen,
  Gift: FaGift,
  HandHoldingHeart: FaHandHoldingHeart,
  HandHoldingMedical: FaHandHoldingMedical,
  HandHoldingUsd: FaHandHoldingUsd,
  HandHoldingWater: FaHandHoldingWater,
  HandHolding: FaHandHolding,
  HandHeart: FaHandHeart,
  IdBadge: FaIdBadge,
  IdCard: FaIdCard,
  Image: FaImage,
  Images: FaImages,
  Info: FaInfo,
  InfoCircle: FaInfoCircle,
  Instagram: FaInstagram,
  JournalWhills: FaJournalWhills,
  Key: FaKey,
  Laptop: FaLaptop,
  LaptopMedical: FaLaptopMedical,
  Leaf: FaLeaf,
  LifeRing: FaLifeRing,
  Lightbulb: FaLightbulb,
  Link: FaLink,
  List: FaList,
  ListAlt: FaListAlt,
  ListOl: FaListOl,
  ListUl: FaListUl,
  Map: FaMap,
  MapMarked: FaMapMarked,
  MapMarkedAlt: FaMapMarkedAlt,
  MapMarker: FaMapMarker,
  MapMarkerAlt: FaMapMarkerAlt,
  MapPin: FaMapPin,
  MapSigns: FaMapSigns,
  Medal: FaMedal,
  Medical: FaMedical,
  MedicalAlt: FaMedicalAlt,
  MoneyBill: FaMoneyBill,
  MoneyBillAlt: FaMoneyBillAlt,
  MoneyBillWave: FaMoneyBillWave,
  MoneyBillWaveAlt: FaMoneyBillWaveAlt,
  MoneyCheck: FaMoneyCheck,
  MoneyCheckAlt: FaMoneyCheckAlt,
  MoneyCheckEdit: FaMoneyCheckEdit,
  MoneyCheckEditAlt: FaMoneyCheckEditAlt,
  Moon: FaMoon,
  Newspaper: FaNewspaper,
  ObjectGroup: FaObjectGroup,
  ObjectUngroup: FaObjectUngroup,
  Outdent: FaOutdent,
  PaintRoller: FaPaintRoller,
  Palette: FaPalette,
  PaperPlane: FaPaperPlane,
  Paperclip: FaPaperclip,
  Paragraph: FaParagraph,
  Paste: FaPaste,
  Pause: FaPause,
  PencilAlt: FaPencilAlt,
  PeopleCarry: FaPeopleCarry,
  Percent: FaPercent,
  Phone: FaPhone,
  PhoneAlt: FaPhoneAlt,
  PhoneSlash: FaPhoneSlash,
  PhoneSquare: FaPhoneSquare,
  PhoneSquareAlt: FaPhoneSquareAlt,
  PhoneVolume: FaPhoneVolume,
  PiggyBank: FaPiggyBank,
  Pills: FaPills,
  Plane: FaPlane,
  PlaneArrival: FaPlaneArrival,
  PlaneDeparture: FaPlaneDeparture,
  Play: FaPlay,
  Plug: FaPlug,
  Plus: FaPlus,
  PlusCircle: FaPlusCircle,
  PlusSquare: FaPlusSquare,
  Podcast: FaPodcast,
  Poll: FaPoll,
  PollH: FaPollH,
  Poop: FaPoop,
  Portrait: FaPortrait,
  PoundSign: FaPoundSign,
  PowerOff: FaPowerOff,
  Prescription: FaPrescription,
  PrescriptionBottle: FaPrescriptionBottle,
  PrescriptionBottleAlt: FaPrescriptionBottleAlt,
  Print: FaPrint,
  Procedures: FaProcedures,
  ProjectDiagram: FaProjectDiagram,
  PuzzlePiece: FaPuzzlePiece,
  Question: FaQuestion,
  QuestionCircle: FaQuestionCircle,
  Receipt: FaReceipt,
  Redo: FaRedo,
  RedoAlt: FaRedoAlt,
  Registered: FaRegistered,
  Reply: FaReply,
  ReplyAll: FaReplyAll,
  Retweet: FaRetweet,
  Ribbon: FaRibbon,
  Road: FaRoad,
  Rocket: FaRocket,
  Rss: FaRss,
  RssSquare: FaRssSquare,
  RubleSign: FaRubleSign,
  RupeeSign: FaRupeeSign,
  Save: FaSave,
  School: FaSchool,
  Screwdriver: FaScrewdriver,
  Search: FaSearch,
  SearchDollar: FaSearchDollar,
  SearchLocation: FaSearchLocation,
  SearchMinus: FaSearchMinus,
  SearchPlus: FaSearchPlus,
  Seedling: FaSeedling,
  Server: FaServer,
  Share: FaShare,
  ShareAlt: FaShareAlt,
  ShareAltSquare: FaShareAltSquare,
  ShareSquare: FaShareSquare,
  ShieldAlt: FaShieldAlt,
  Ship: FaShip,
  ShippingFast: FaShippingFast,
  ShoePrints: FaShoePrints,
  ShoppingBag: FaShoppingBag,
  ShoppingBasket: FaShoppingBasket,
  ShoppingCart: FaShoppingCart,
  Shower: FaShower,
  ShuttleVan: FaShuttleVan,
  Sign: FaSign,
  SignInAlt: FaSignInAlt,
  SignLanguage: FaSignLanguage,
  SignOutAlt: FaSignOutAlt,
  Signal: FaSignal,
  Sitemap: FaSitemap,
  Skull: FaSkull,
  SlidersH: FaSlidersH,
  Smile: FaSmile,
  SmileBeam: FaSmileBeam,
  SmileWink: FaSmileWink,
  Snowflake: FaSnowflake,
  Sort: FaSort,
  SortAlphaDown: FaSortAlphaDown,
  SortAlphaUp: FaSortAlphaUp,
  SortAmountDown: FaSortAmountDown,
  SortAmountUp: FaSortAmountUp,
  SortDown: FaSortDown,
  SortNumericDown: FaSortNumericDown,
  SortNumericUp: FaSortNumericUp,
  SortUp: FaSortUp,
  SpaceShuttle: FaSpaceShuttle,
  Spinner: FaSpinner,
  Square: FaSquare,
  Star: FaStar,
  StarHalf: FaStarHalf,

  StepBackward: FaStepBackward,
  StepForward: FaStepForward,
  Stethoscope: FaStethoscope,
  StickyNote: FaStickyNote,
  Stop: FaStop,
  Stopwatch: FaStopwatch,
  Store: FaStore,
  StoreAlt: FaStoreAlt,
  Stream: FaStream,
  StreetView: FaStreetView,
  Strikethrough: FaStrikethrough,
  Stroopwafel: FaStroopwafel,
  Subscript: FaSubscript,
  Subway: FaSubway,
  Suitcase: FaSuitcase,
  Sun: FaSun,
  Superscript: FaSuperscript,
  Sync: FaSync,
  SyncAlt: FaSyncAlt,
  Syringe: FaSyringe,
  Table: FaTable,
  Tablet: FaTablet,
  TabletAlt: FaTabletAlt,
  TachometerAlt: FaTachometerAlt,
  Tag: FaTag,
  Tags: FaTags,
  Tape: FaTape,
  Tasks: FaTasks,
  Taxi: FaTaxi,
  Teeth: FaTeeth,
  TeethOpen: FaTeethOpen,
  Terminal: FaTerminal,
  TextHeight: FaTextHeight,
  TextWidth: FaTextWidth,
  Th: FaTh,
  ThLarge: FaThLarge,
  ThList: FaThList,
  Thermometer: FaThermometer,
  ThermometerEmpty: FaThermometerEmpty,
  ThermometerFull: FaThermometerFull,
  ThermometerHalf: FaThermometerHalf,
  ThermometerQuarter: FaThermometerQuarter,
  ThermometerThreeQuarters: FaThermometerThreeQuarters,
  ThumbsDown: FaThumbsDown,
  ThumbsUp: FaThumbsUp,
  Thumbtack: FaThumbtack,
  TicketAlt: FaTicketAlt,
  Times: FaTimes,
  TimesCircle: FaTimesCircle,
  Tint: FaTint,
  TintSlash: FaTintSlash,
  Tired: FaTired,
  ToggleOff: FaToggleOff,
  ToggleOn: FaToggleOn,
  Toilet: FaToilet,
  ToiletPaper: FaToiletPaper,
  Toolbox: FaToolbox,
  Tools: FaTools,
  Tooth: FaTooth,
  Trademark: FaTrademark,
  Undo: FaUndo,
  UndoAlt: FaUndoAlt,
  UniversalAccess: FaUniversalAccess,
  University: FaUniversity,
  Unlink: FaUnlink,
  Unlock: FaUnlock,
  UnlockAlt: FaUnlockAlt,
  Upload: FaUpload,
  User: FaUser,
  UserAlt: FaUserAlt,
  UserAltSlash: FaUserAltSlash,
  UserAstronaut: FaUserAstronaut,
  UserCheck: FaUserCheck,
  UserCircle: FaUserCircle,
  UserClock: FaUserClock,
  UserCog: FaUserCog,
  UserEdit: FaUserEdit,
  UserFriends: FaUserFriends,
  UserGraduate: FaUserGraduate,
  UserLock: FaUserLock,
  UserMd: FaUserMd,
  UserMinus: FaUserMinus,
  UserNinja: FaUserNinja,
  UserPlus: FaUserPlus,
  UserSecret: FaUserSecret,
  UserShield: FaUserShield,
  UserSlash: FaUserSlash,
  UserTag: FaUserTag,
  UserTie: FaUserTie,
  UserTimes: FaUserTimes,
  Users: FaUsers,
  UsersCog: FaUsersCog,
  UtensilSpoon: FaUtensilSpoon,
  Utensils: FaUtensils,
  VectorSquare: FaVectorSquare,
  Venus: FaVenus,
  VenusDouble: FaVenusDouble,
  VenusMars: FaVenusMars,
  Vial: FaVial,
  Vials: FaVials,
  Video: FaVideo,
  VideoSlash: FaVideoSlash,
  Vihara: FaVihara,
  VolumeDown: FaVolumeDown,
  VolumeMute: FaVolumeMute,
  VolumeOff: FaVolumeOff,
  VolumeUp: FaVolumeUp,
  Walking: FaWalking,
  Wallet: FaWallet,
  Warehouse: FaWarehouse,
  Weight: FaWeight,
  WeightHanging: FaWeightHanging,
  Wheelchair: FaWheelchair,
  Wifi: FaWifi,
  WindowClose: FaWindowClose,
  WindowMaximize: FaWindowMaximize,
  WindowMinimize: FaWindowMinimize,
  WindowRestore: FaWindowRestore,
  WineGlass: FaWineGlass,
  WonSign: FaWonSign,
  Wrench: FaWrench,
  XRay: FaXRay,
};

export default icons;
